### ISSUE TITLE
Broken link in Help page

### ISSUE THREAD

**Issue by FranckCo** [Colectica/ddiregistry#6]
Hello

Le link to "Register" in the [main page](https://registry.ddialliance.org/) goes to https://registry.ddialliance.org/Identity/Account/Register, which is OK, but on the [Help page](https://registry.ddialliance.org/Help) the link is to https://registry.ddialliance.org/Account/Register which returns a 404.

**Comment by DanSmith** [comment]
The update in [5180b67](https://github.com/Colectica/ddiregistry/commit/5180b677698b32af7e608d68176e115ed66c93c9) has been deployed. Thanks Franck
